config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new"
    get "login", :to => "devise/sessions#new"
    get "register", :to => "devise/registrations#new"
    get "logout", :to => "devise/sessions#destroy"
    get "profile", :to => "devise/registrations#edit"
  end
  root to: "welcome#index"
  resources :history_balls
  resources :double_balls do
    collection do
      get 'list_show'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/history_ball.rb
# == Schema Information
#
# Table name: history_balls
#
#  id            :integer          not null, primary key
#  period_number :string(255)
#  date          :datetime
#  red1          :integer
#  red2          :integer
#  red3          :integer
#  red4          :integer
#  red5          :integer
#  red6          :integer
#  blue          :integer
#  week_num      :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class HistoryBall < ApplicationRecord
end

app/controllers/history_balls_controller.rb
class HistoryBallsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_history_ball, only: [:show, :edit, :update, :destroy]

  # GET /history_balls
  # GET /history_balls.json
  def index
    @history_balls = HistoryBall.all.paginate(page:params[:page],per_page:10)
  end

  # GET /history_balls/1
  # GET /history_balls/1.json
  def show
  end

  # GET /history_balls/new
  def new
    @history_ball = HistoryBall.new
  end

  # GET /history_balls/1/edit
  def edit
  end

  # POST /history_balls
  # POST /history_balls.json
  def create
    @history_ball = HistoryBall.new(history_ball_params)

    respond_to do |format|
      if @history_ball.save
        format.html { redirect_to @history_ball, notice: 'History ball was successfully created.' }
        format.json { render :show, status: :created, location: @history_ball }
      else
        format.html { render :new }
        format.json { render json: @history_ball.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /history_balls/1
  # PATCH/PUT /history_balls/1.json
  def update
    respond_to do |format|
      if @history_ball.update(history_ball_params)
        format.html { redirect_to @history_ball, notice: 'History ball was successfully updated.' }
        format.json { render :show, status: :ok, location: @history_ball }
      else
        format.html { render :edit }
        format.json { render json: @history_ball.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /history_balls/1
  # DELETE /history_balls/1.json
  def destroy
    @history_ball.destroy
    respond_to do |format|
      format.html { redirect_to history_balls_url, notice: 'History ball was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_history_ball
      @history_ball = HistoryBall.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def history_ball_params
      params.require(:history_ball).permit(:period_number, :date, :red1, :red2, :red3, :red4, :red5, :red6, :blue, :week_num)
    end
end

app/helpers/history_balls_helper.rb
module HistoryBallsHelper
end

app/views/history_balls/_form.html.erb
<%= form_for(history_ball) do |f| %>
  <% if history_ball.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(history_ball.errors.count, "error") %> prohibited this history_ball from being saved:</h2>

      <ul>
      <% history_ball.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :period_number %>
    <%= f.text_field :period_number %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.datetime_select :date %>
  </div>

  <div class="field">
    <%= f.label :red1 %>
    <%= f.number_field :red1 %>
  </div>

  <div class="field">
    <%= f.label :red2 %>
    <%= f.number_field :red2 %>
  </div>

  <div class="field">
    <%= f.label :red3 %>
    <%= f.number_field :red3 %>
  </div>

  <div class="field">
    <%= f.label :red4 %>
    <%= f.number_field :red4 %>
  </div>

  <div class="field">
    <%= f.label :red5 %>
    <%= f.number_field :red5 %>
  </div>

  <div class="field">
    <%= f.label :red6 %>
    <%= f.number_field :red6 %>
  </div>

  <div class="field">
    <%= f.label :blue %>
    <%= f.number_field :blue %>
  </div>

  <div class="field">
    <%= f.label :week_num %>
    <%= f.number_field :week_num %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/history_balls/edit.html.erb
<h1>Editing History Ball</h1>

<%= render 'form', history_ball: @history_ball %>

<%= link_to 'Show', @history_ball %> |
<%= link_to 'Back', history_balls_path %>

app/views/history_balls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>History Balls</h1>
<%= will_paginate @questions %>

<table>
  <thead>
    <tr>
      <th><%= I18n.t :"history_ball.period_number" %></th>
      <th><%= I18n.t :"history_ball.date" %></th>
      <th><%= I18n.t :"history_ball.week_num" %></th>
      <th><%= I18n.t :"history_ball.red1" %></th>
      <th><%= I18n.t :"history_ball.red2" %></th>
      <th><%= I18n.t :"history_ball.red3" %></th>
      <th><%= I18n.t :"history_ball.red4" %></th>
      <th><%= I18n.t :"history_ball.red5" %></th>
      <th><%= I18n.t :"history_ball.red6" %></th>
      <th><%= I18n.t :"history_ball.blue" %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @history_balls.each do |history_ball| %>
      <tr>
        <td><%= history_ball.period_number %></td>
        <td><%= history_ball.date %></td>
        <td><%= history_ball.week_num %></td>
        <td><%= history_ball.red1 %></td>
        <td><%= history_ball.red2 %></td>
        <td><%= history_ball.red3 %></td>
        <td><%= history_ball.red4 %></td>
        <td><%= history_ball.red5 %></td>
        <td><%= history_ball.red6 %></td>
        <td><%= history_ball.blue %></td>
        <td><%= link_to 'Show', history_ball %></td>
        <td><%= link_to 'Edit', edit_history_ball_path(history_ball) %></td>
        <td><%= link_to 'Destroy', history_ball, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= will_paginate @questions %>

<%= link_to 'New History Ball', new_history_ball_path %>

app/views/history_balls/new.html.erb
<h1>New History Ball</h1>

<%= render 'form', history_ball: @history_ball %>

<%= link_to 'Back', history_balls_path %>

app/views/history_balls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Period number:</strong>
  <%= @history_ball.period_number %>
</p>

<p>
  <strong>Date:</strong>
  <%= @history_ball.date %>
</p>

<p>
  <strong>Red1:</strong>
  <%= @history_ball.red1 %>
</p>

<p>
  <strong>Red2:</strong>
  <%= @history_ball.red2 %>
</p>

<p>
  <strong>Red3:</strong>
  <%= @history_ball.red3 %>
</p>

<p>
  <strong>Red4:</strong>
  <%= @history_ball.red4 %>
</p>

<p>
  <strong>Red5:</strong>
  <%= @history_ball.red5 %>
</p>

<p>
  <strong>Red6:</strong>
  <%= @history_ball.red6 %>
</p>

<p>
  <strong>Blue:</strong>
  <%= @history_ball.blue %>
</p>

<p>
  <strong>Week num:</strong>
  <%= @history_ball.week_num %>
</p>

<%= link_to 'Edit', edit_history_ball_path(@history_ball) %> |
<%= link_to 'Back', history_balls_path %>