config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new"
    get "login", :to => "devise/sessions#new"
    get "register", :to => "devise/registrations#new"
    get "logout", :to => "devise/sessions#destroy"
    get "profile", :to => "devise/registrations#edit"
  end
  root to: "welcome#index"
  resources :history_balls
  resources :double_balls do
    collection do
      get 'list_show'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/double_ball.rb
# == Schema Information
#
# Table name: double_balls
#
#  id            :integer          not null, primary key
#  period_number :string(255)
#  date          :datetime
#  red1          :integer
#  red2          :integer
#  red3          :integer
#  red4          :integer
#  red5          :integer
#  red6          :integer
#  blue          :integer
#  week_num      :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class DoubleBall < ApplicationRecord

  def red_total
    return (red1 + red2 + red3 + red4 + red5 + red6)
  end
  def get_zhishu
    arr = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31]
    n = 0
    n += 1 if arr.include? red1
    n += 1 if arr.include? red2
    n += 1 if arr.include? red3
    n += 1 if arr.include? red4
    n += 1 if arr.include? red5
    n += 1 if arr.include? red6
    return n
  end
  def is_have_red(set_number)
    r_n = 0
    arr = [red1, red2, red3, red4, red5, red6]
    r_n += 1 if arr.include? set_number
    r_n += 1 if arr.include? set_number
    r_n += 1 if arr.include? set_number
    r_n += 1 if arr.include? set_number
    r_n += 1 if arr.include? set_number
    r_n += 1 if arr.include? set_number
    return r_n
  end
  def is_have_blue(set_number)
    b_n = 0
    b_n += 1 if set_number == blue
    return b_n
  end
  def get_week_day
    weekday = "星期"
    case week_num
    when 0
      weekday += "日"
    when 1
      weekday += "一"
    when 2
      weekday += "二"
    when 3
      weekday += "三"
    when 4
      weekday += "四"
    when 5
      weekday += "五"
    when 6
      weekday += "六"
    else
      weekday += "?"
    end
    return weekday
  end
  def ji_ou_number
    arr_j = 0
    arr_j += 1 if red1 % 2 != 0
    arr_j += 1 if red2 % 2 != 0
    arr_j += 1 if red3 % 2 != 0
    arr_j += 1 if red4 % 2 != 0
    arr_j += 1 if red5 % 2 != 0
    arr_j += 1 if red6 % 2 != 0
    return arr_j
  end
  def self.hello
    DoubleBall.destroy_all
    r_arr = []
    b_arr = []
    (1..33).each do |index|
      r_arr.push(index)
      b_arr.push(index) if index < 17
    end
    (1..10000).each do |index1|
      arr0 = []
      arr0 = r_arr.sample(6).sort + b_arr.sample(1)
      this_date = Time.new + index1.days
      DoubleBall.create!(period_number: "2016-#{index1}", date: this_date, red1: arr0[0], red2: arr0[1], red3: arr0[2],
        red4: arr0[3], red5: arr0[4], red6: arr0[5], blue: arr0[6], week_num: this_date.wday)
    end
  end
end

app/controllers/double_balls_controller.rb
class DoubleBallsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_double_ball, only: [:show, :edit, :update, :destroy]

  # GET /double_balls
  # GET /double_balls.json
  def index
    @double_balls = DoubleBall.all.paginate(page:params[:page],per_page:10)
  end

  def list_show
    @double_balls = DoubleBall.all.paginate(page:params[:page],per_page:10)
  end

  # GET /double_balls/1
  # GET /double_balls/1.json
  def show
  end

  # GET /double_balls/new
  def new
    @double_ball = DoubleBall.new
  end

  # GET /double_balls/1/edit
  def edit
  end

  # POST /double_balls
  # POST /double_balls.json
  def create
    @double_ball = DoubleBall.new(double_ball_params)

    respond_to do |format|
      if @double_ball.save
        format.html { redirect_to @double_ball, notice: 'Double ball was successfully created.' }
        format.json { render :show, status: :created, location: @double_ball }
      else
        format.html { render :new }
        format.json { render json: @double_ball.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /double_balls/1
  # PATCH/PUT /double_balls/1.json
  def update
    respond_to do |format|
      if @double_ball.update(double_ball_params)
        format.html { redirect_to @double_ball, notice: 'Double ball was successfully updated.' }
        format.json { render :show, status: :ok, location: @double_ball }
      else
        format.html { render :edit }
        format.json { render json: @double_ball.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /double_balls/1
  # DELETE /double_balls/1.json
  def destroy
    @double_ball.destroy
    respond_to do |format|
      format.html { redirect_to double_balls_url, notice: 'Double ball was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_double_ball
      @double_ball = DoubleBall.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def double_ball_params
      params.require(:double_ball).permit(:period_number, :date, :red1, :red2, :red3, :red4, :red5, :red6, :blue, :week_num)
    end
end

app/helpers/double_balls_helper.rb
module DoubleBallsHelper
end

app/views/double_balls/_form.html.erb
<%= bootstrap_form_for(double_ball) do |f| %>
  <% if double_ball.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(double_ball.errors.count, "error") %> prohibited this double_ball from being saved:</h2>

      <ul>
      <% double_ball.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :period_number %>
  </div>

  <div class="field">
    <%= f.datetime_select :date %>
  </div>

  <div class="field">
    <%= f.number_field :red1 %>
  </div>

  <div class="field">
    <%= f.number_field :red2 %>
  </div>

  <div class="field">
    <%= f.number_field :red3 %>
  </div>

  <div class="field">
    <%= f.number_field :red4 %>
  </div>

  <div class="field">
    <%= f.number_field :red5 %>
  </div>

  <div class="field">
    <%= f.number_field :red6 %>
  </div>

  <div class="field">
    <%= f.number_field :blue %>
  </div>

  <div class="field">
    <%= f.number_field :week_num %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/double_balls/edit.html.erb
<h1>Editing Double Ball</h1>

<%= render 'form', double_ball: @double_ball %>

<%= link_to 'Show', @double_ball %> |
<%= link_to 'Back', double_balls_path %>

app/views/double_balls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Double Balls</h1>
<%= will_paginate @questions %>
<table>
  <thead>
    <tr>
      <th><%= I18n.t :"double_ball.period_number" %></th>
      <th><%= I18n.t :"double_ball.date" %></th>
      <th><%= I18n.t :"double_ball.week_num" %></th>
      <th><%= I18n.t :"double_ball.red1" %></th>
      <th><%= I18n.t :"double_ball.red2" %></th>
      <th><%= I18n.t :"double_ball.red3" %></th>
      <th><%= I18n.t :"double_ball.red4" %></th>
      <th><%= I18n.t :"double_ball.red5" %></th>
      <th><%= I18n.t :"double_ball.red6" %></th>
      <th><%= I18n.t :"double_ball.blue" %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @double_balls.each do |double_ball| %>
    <tr>
      <td><%= double_ball.period_number %></td>
      <td><%= double_ball.date.strftime('%Y-%m-%d') %></td>
      <td>
        <%= double_ball.get_week_day %>
      </td>
      <td><%= double_ball.red1 %></td>
      <td><%= double_ball.red2 %></td>
      <td><%= double_ball.red3 %></td>
      <td><%= double_ball.red4 %></td>
      <td><%= double_ball.red5 %></td>
      <td><%= double_ball.red6 %></td>
      <td><%= double_ball.blue %></td>
      <td><%= link_to 'Show', double_ball %></td>
      <td><%= link_to 'Edit', edit_double_ball_path(double_ball) %></td>
      <td><%= link_to 'Destroy', double_ball, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= will_paginate @questions %>
<%= link_to 'New Double Ball', new_double_ball_path %>

app/views/double_balls/list_show.html.erb
<p id="notice"><%= notice %></p>

<h1>Double Balls</h1>
<%= will_paginate @questions %>
<table class="table table-striped table-hover table-auto">
  <thead>
    <tr>
      <th><%= I18n.t :"double_ball.period_number" %></th>
      <th><%= I18n.t :"double_ball.date" %></th>
      <th><%= I18n.t :"double_ball.week_num" %></th>
      <th class="red"><%= I18n.t :"double_ball.red1" %></th>
      <th class="red"><%= I18n.t :"double_ball.red2" %></th>
      <th class="red"><%= I18n.t :"double_ball.red3" %></th>
      <th class="red"><%= I18n.t :"double_ball.red4" %></th>
      <th class="red"><%= I18n.t :"double_ball.red5" %></th>
      <th class="red"><%= I18n.t :"double_ball.red6" %></th>
      <th class="blue"><%= I18n.t :"double_ball.blue" %></th>
      <% (1..33).each do |r| %>
      <th class="red"><%= r %></th>
      <% end %>
      <% (1..16).each do |b| %>
      <th class="blue"><%= b %></th>
      <% end %>
      <th>奇数</th>
      <th>偶数</th>
      <th>质数</th>
      <th>合数</th>
      <th>红和</th>
      <th>总和</th>
    </tr>
  </thead>

  <tbody>
    <% @double_balls.each do |double_ball| %>
      <tr>
        <td><%= double_ball.period_number %></td>
        <td><%= double_ball.date.strftime('%Y-%m-%d') %></td>
        <td><%= double_ball.get_week_day %></td>
        <td class="red"><%= double_ball.red1 %></td>
        <td class="red"><%= double_ball.red2 %></td>
        <td class="red"><%= double_ball.red3 %></td>
        <td class="red"><%= double_ball.red4 %></td>
        <td class="red"><%= double_ball.red5 %></td>
        <td class="red"><%= double_ball.red6 %></td>
        <td class="blue"><%= double_ball.blue %></td>
        <% (1..33).each do |r| %>
        <th class="<% if double_ball.is_have_red(r) > 0 %> red : ''<% end%>"><%= r %></th>
        <% end %>
        <% (1..16).each do |b| %>
        <th class="<% if double_ball.is_have_blue(b) > 0 %> blue : ''<% end%>"><%= b %></th>
        <% end %>

        <td><%= double_ball.ji_ou_number %></td>
        <td><%= 6 - double_ball.ji_ou_number %></td>
        <td><%= double_ball.get_zhishu %></td>
        <td><%= 6 - double_ball.get_zhishu %></td>
        <td><%= double_ball.red_total %></td>
        <td><%= double_ball.red_total + double_ball.blue %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @questions %>

app/views/double_balls/new.html.erb
<h1>New Double Ball</h1>

<%= render 'form', double_ball: @double_ball %>

<%= link_to 'Back', double_balls_path %>

app/views/double_balls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Period number:</strong>
  <%= @double_ball.period_number %>
</p>

<p>
  <strong>Date:</strong>
  <%= @double_ball.date %>
</p>

<p>
  <strong>Red1:</strong>
  <%= @double_ball.red1 %>
</p>

<p>
  <strong>Red2:</strong>
  <%= @double_ball.red2 %>
</p>

<p>
  <strong>Red3:</strong>
  <%= @double_ball.red3 %>
</p>

<p>
  <strong>Red4:</strong>
  <%= @double_ball.red4 %>
</p>

<p>
  <strong>Red5:</strong>
  <%= @double_ball.red5 %>
</p>

<p>
  <strong>Red6:</strong>
  <%= @double_ball.red6 %>
</p>

<p>
  <strong>Blue:</strong>
  <%= @double_ball.blue %>
</p>

<p>
  <strong>Week num:</strong>
  <%= @double_ball.week_num %>
</p>

<%= link_to 'Edit', edit_double_ball_path(@double_ball) %> |
<%= link_to 'Back', double_balls_path %>